# Generated by Django 5.1.1 on 2025-03-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_art_remove_artupload_id_artupload_art_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artupload',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000000000),
        ),
        migrations.AlterField(
            model_name='artupload',
            name='art_price',
            field=models.DecimalField(decimal_places=2, max_digits=1000000000),
        ),
    ]
