# Generated by Django 5.1.1 on 2025-03-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_artupload_art_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artupload',
            name='art_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='artupload',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
